#!/bin/bash
# init-env.sh - Runs on HOST before containers start
# Creates .env file for docker-compose with appropriate URLs
# AND pre-initializes project directory for backend container

set -euo pipefail

cd "$(dirname "$0")"

SEMIONT_VERSION="${SEMIONT_VERSION:-0.2.0}"

# Check if running in Codespaces
if [ -n "${CODESPACE_NAME:-}" ]; then
    echo "Detected Codespaces environment: ${CODESPACE_NAME}"

    FRONTEND_URL="https://${CODESPACE_NAME}-3000.app.github.dev"
    BACKEND_URL="https://${CODESPACE_NAME}-4000.app.github.dev"
    SITE_DOMAIN="${CODESPACE_NAME}-3000.app.github.dev"

    cat > .env <<EOF
# Codespaces URLs (generated by init-env.sh)
NEXT_PUBLIC_API_URL=${BACKEND_URL}
NEXTAUTH_URL=${FRONTEND_URL}
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=${SITE_DOMAIN}
SEMIONT_VERSION=${SEMIONT_VERSION}
EOF

    echo "Created .env with Codespaces URLs"
else
    echo "Local environment detected"

    FRONTEND_URL="http://localhost:3000"
    BACKEND_URL="http://localhost:4000"
    SITE_DOMAIN="localhost:3000"

    # Create .env with localhost URLs
    cat > .env <<EOF
# Local URLs (generated by init-env.sh)
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=
SEMIONT_VERSION=${SEMIONT_VERSION}
EOF

    echo "Created .env with localhost URLs"
fi

# Install Node.js 22.x
echo "Installing Node.js 22.x..."
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs
echo "  ✓ Node.js $(node --version) installed"

# Install @semiont/cli to run semiont init
echo "Installing @semiont/cli@latest..."
npm install -g "@semiont/cli@latest"
echo "  ✓ CLI installed"

# Pre-initialize project directory for backend container
# This must happen BEFORE docker-compose starts the backend
echo "Initializing project directory for backend container..."

PROJECT_DIR="../project"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Run semiont init to create initial project structure
echo "Running semiont init..."
npx --yes "@semiont/cli@latest" init
echo "  ✓ Project initialized with semiont init"

# Overwrite with our templates
echo "Copying configuration templates..."
cp ../.devcontainer/semiont.json semiont.json
cp ../.devcontainer/environments-demo.json environments/demo.json
echo "  ✓ Templates copied"

# Update URLs in demo.json for the detected environment
if [ -n "${CODESPACE_NAME:-}" ]; then
    echo "Updating Codespaces URLs in configuration..."
    node -e "
    const fs = require('fs');
    const baseConfig = JSON.parse(fs.readFileSync('semiont.json', 'utf-8'));
    const envFile = 'environments/demo.json';
    const config = JSON.parse(fs.readFileSync(envFile, 'utf-8'));
    config.site.domain = '${SITE_DOMAIN}';
    config.site.oauthAllowedDomains = ['${SITE_DOMAIN}', ...(baseConfig.site?.oauthAllowedDomains || [])];
    config.services.frontend.url = '${FRONTEND_URL}';
    config.services.backend.publicURL = '${BACKEND_URL}';
    config.services.backend.corsOrigin = '${FRONTEND_URL}';
    fs.writeFileSync(envFile, JSON.stringify(config, null, 2));
    "
    echo "  ✓ URLs configured for Codespaces"
fi

cd ../.devcontainer
echo "✓ Project directory initialized at $PROJECT_DIR"
