#!/bin/bash
# init-env.sh - Runs on HOST before containers start
# Creates .env file for docker-compose with appropriate URLs

set -euo pipefail

cd "$(dirname "$0")"

# Check if running in Codespaces
if [ -n "${CODESPACE_NAME:-}" ]; then
    echo "Detected Codespaces environment: ${CODESPACE_NAME}"

    FRONTEND_URL="https://${CODESPACE_NAME}-3000.app.github.dev"
    BACKEND_URL="https://${CODESPACE_NAME}-4000.app.github.dev"
    SITE_DOMAIN="${CODESPACE_NAME}-3000.app.github.dev"

    cat > .env <<EOF
# Codespaces URLs (generated by init-env.sh)
NEXT_PUBLIC_API_URL=${BACKEND_URL}
NEXTAUTH_URL=${FRONTEND_URL}
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=${SITE_DOMAIN}
SEMIONT_VERSION=${SEMIONT_VERSION:-0.2.0}
EOF

    echo "Created .env with Codespaces URLs"
else
    echo "Local environment detected"

    # Create .env with localhost URLs
    cat > .env <<EOF
# Local URLs (generated by init-env.sh)
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=
SEMIONT_VERSION=${SEMIONT_VERSION:-0.2.0}
EOF

    echo "Created .env with localhost URLs"
fi
